name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cargo clippy
      run: cargo clippy --verbose --all-features -- -D warnings

    - name: cargo build
      run: cargo build --verbose

    - name: cargo test
      run: cargo test --verbose
